### ISSUE TITLE
Feature requests (Copied from youtube)

### ISSUE THREAD

**Issue by FFRyan** [kgmonteith/KSPSBC#1]
Hey man, I'm absolutely amazed by the work you've done. It's so much fun to use and way better than using the default file the controller comes with. I do have 2 requests though since I don't really have that much of a clue what I'm doing. It would be really cool if there was a way to have keep all the lights on but have them dimmed when not being held down/toggled. I ripped this out of a previous file I used but the lights turn off once they are pressed if it is put in the initialize section and it overrides other light states when put in the other (public voids?). I guess it has something to do with adding an if else to it with a 2nd variable.

int litIntensity = 3;

for (int i = 1; i <= 33; i++)
{

controller.SetLEDState((ControllerLEDEnum)(i), litIntensity, true);

}

The other thing I'd like to ask about is if there is a way to make the (constructor?) for the flashingLight to have 3 stages of brightness/duration. I think I was close to figuring that one out but ultimately had to give up on that.

**Comment by kgmonteith** [comment]
Multi-level light support added in release v1.0.1. See the code for example use.

Setting a minimum light level requires changes to steel-batallion-64, the package this mod relies on. I'm working on those changes, but I'm not the project owner, so I can't commit it. I'll either try to get it pushed into the actual steel-batallion-64 project, or I'll publish my own (unsupported) version of the software. I'll post a new comment here once that is resolved.
